apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-bgp-agent-config
  namespace: openshift-ovn-kubernetes
data:
  driver: vpnv4
  rd_base: "65000"
  rt_base: "65000"
  router_id: "10.255.0.2"
  neighbors: |
    - address: 192.0.2.11
      remote_asn: 65101
    - address: 192.0.2.12
      remote_asn: 65102
    - address: 192.0.2.13
      remote_asn: 65103

