apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-bgp-agent-config
  namespace: openshift-ovn-kubernetes
data:
  vpnv4.yaml: |
    driver:
      local_asn: 65000
      router_id: 10.255.0.2
      rd_base: 65000
      rt_base: 65000
      output_dir: /etc/frr
      include_globals: true
      maintain_empty_vrf: true
      neighbours:
        - address: 192.0.2.11
          remote_asn: 65101
        - address: 192.0.2.12
          remote_asn: 65102
        - address: 192.0.2.13
          remote_asn: 65103
    tenants.json: |
      {
        "tenants": [
          {"namespace": "demo", "prefixes": ["10.244.0.0/24"]},
          {"namespace": "demo-b", "prefixes": ["10.245.0.0/24"]}
        ]
      }

