kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ovn-bgp-lab
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction
        controllerManager:
          extraArgs:
            node-cidr-mask-size: "24"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
  - role: worker
    image: kindest/node:v1.30.0
  - role: worker
    image: kindest/node:v1.30.0


